### ISSUE TITLE
Add Information About Accommodations, Food, etc.

### ISSUE THREAD

**Issue by dhamburger** [ronnyb29/medhacksSite#26]
We want to have one of the FAQ sections address food and lodging, probably. Also, a brief guide to campus and Baltimore might be useful to upload as part of a 'Welcome to MedHacks' packet.

**Comment by dhamburger** [comment]
We could contact Hopkins Hosting or the Colonnade if we want off-site evening options.

**Comment by ronboger** [comment]
@dhamburger this should most def go on the site. could you copy the text you want on it here?

**Comment by dhamburger** [comment]
All meals, swag, and extra food (plenty of it), will be provided throughout MedHacks.

**Comment by dhamburger** [comment]
We need to add information about vegetarian, Kosher, etc. options if they're available.
