### ISSUE TITLE
make page for code of conduct

### ISSUE THREAD

**Issue by ronboger** [ronnyb29/medhacksSite#29]

**Comment by ronboger** [comment]
let's make this a pdf. @dhamburger do you think you could make it look like Elizabeth's info packet?

**Comment by ronboger** [comment]
if you check the medhacks email there's the file .pages she did it on, but i don't know how to open it

**Comment by dhamburger** [comment]
I can't open it, either.

**Comment by ronboger** [comment]
medhacks.org/conduct.pdf
