### ISSUE TITLE
add info on sleep

### ISSUE THREAD

**Issue by ronboger** [ronnyb29/medhacksSite#31]

**Comment by ronboger** [comment]
@dhamburger comment the text here

**Comment by dhamburger** [comment]
For those coming in from out of town, we recommend you bring a sleeping bag and basic toiletries. If hotels sound better than a floor, the Doubletree Colonnade is a two-minute walk. Other hotels in the Inner Harbor area are reachable by cab. A limited number of hosting opportunities may be available - we will send out details as soon as possible.
