### ISSUE TITLE
not responsive on my moto x

### ISSUE THREAD

**Issue by ronboger** [ronnyb29/medhacksSite#34]
will post pictures later

**Comment by baileyparker** [comment]
What are the screen dimensions (virtual if retina and actual) in pixels?

**Comment by ronboger** [comment]
![image](https://cloud.githubusercontent.com/assets/8752064/9674802/8d712c4a-5283-11e5-9e44-65b6dfd79a7f.png)

**Comment by ronboger** [comment]
![image](https://cloud.githubusercontent.com/assets/8752064/9674806/94fd7efa-5283-11e5-9c2f-c6c4e9e82cc6.png)

**Comment by ronboger** [comment]
last commit doesn't fix :(
