### ISSUE TITLE
App is not very encouraging of other schools (despite disclaimer)

### ISSUE THREAD

**Issue by dwesty** [ronnyb29/medhacksSite#35]
Remember when you were a kid and were the last one picked for basketball? I do. You know how that made me feel? It made be feel like "other". That feeling sucks, and it turned me into the monster I am today.

IMHO this should be 100% open field.  I don't understand why having this data is important. We might have turned away hundreds of people.

![image](https://cloud.githubusercontent.com/assets/6182431/9673859/e849f82a-5276-11e5-8800-0551ab7675cf.png)

If I were applying to MIT hackathon and they listed 10 MIT schools and there's an "other" field, I would close that tab. That's the quickest way to say "This is not for me" despite the fact that we have that disclaimer at the top.

**Comment by ronboger** [comment]
great point.

**Comment by ronboger** [comment]
we do need a way to track what type (hacker, dev, entrepreneur) people are, and we would like to know what school in general

**Comment by ronboger** [comment]
fixed
