### ISSUE TITLE
add navbar/menu

### ISSUE THREAD

**Issue by ronboger** [ronnyb29/medhacksSite#4]

**Comment by ronboger** [comment]
links to help:

https://www.google.com/search?q=make+navbar+appear+on+scroll&oq=make+navbar+app&aqs=chrome.0.0j69i57.4063j1j7&sourceid=chrome&es_sm=91&ie=UTF-8#q=make+navbar+appear+on+scroll+bootstrap

http://stackoverflow.com/questions/14667829/how-to-create-a-sticky-navigation-bar-that-becomes-fixed-to-the-top-after-scroll

http://stackoverflow.com/questions/17687172/bootstrap-make-a-navbar-sticky-after-scrolling-down

**Comment by ronboger** [comment]
another http://mycookroom.ru/mywork/Aurora-v1.1.1-Demo/Site/Slideshow/

**Comment by baileyparker** [comment]
![image](https://cloud.githubusercontent.com/assets/7943649/9647166/3bf34adc-51a8-11e5-8b1b-c869042ddcf2.png)

Fixed by ff289b92e3891bf273b66cfa9a1bd817165e8d76.

**Comment by ronboger** [comment]
hahahaha
