### ISSUE TITLE
Page is wide (on MacBook air)

### ISSUE THREAD

**Issue by dhamburger** [ronnyb29/medhacksSite#42]
Not sure if this is a localized issue, but the page is on the far left of a very wide field.

**Comment by baileyparker** [comment]
![Pics or it didn't happen](http://pixel-pushers-book.com/wp-content/uploads/2015/03/pics_or_it_didnt_happen_retro_tshirt-p235350460184511443qj9v_328_zpsa77184e3.jpg)

**Comment by ronboger** [comment]
@dhamburger he wants you to screenshot your screen and post it so he can see :)

**Comment by dhamburger** [comment]
Ron suspects this is a Firefox compatibility issue.
![screen shot 2015-09-09 at 6 17 20 pm](https://cloud.githubusercontent.com/assets/14101123/9800433/f2fbb880-57da-11e5-975d-9f89a72397a6.png)

**Comment by ronboger** [comment]
fixed in f600d54967917cfcd2e106ecdd4d71c46abef706
