### ISSUE TITLE
add details on travel

### ISSUE THREAD

**Issue by ronboger** [ronnyb29/medhacksSite#44]

**Comment by dhamburger** [comment]
MedHacks 2015 will be able to offer a limited number of travel grants for participants coming from outside the Baltimore metro area. These grants will be capped at $100 per applicant, and will be determined on a need-based set of criteria. If you are in need of assistance in attending MedHacks, and live outside the Baltimore area, please send an email to medhacks@jhu.edu with the subject "MedHacks Travel Grant." Emails should include participant name, year, school, and the location from which they will be traveling to Baltimore.

For participants coming to the Homewood Campus from the Medical School Campus, and from the Bloomberg School of Public Health, the JHMI shuttle is recommended. The JHMI shuttle, which is free for JHU students and affiliates, runs routinely and stops outside the Charles Street entrance to the Milton S. Eisenhower Library on the Homewood Campus. From here, participants should follow signage and campus maps to the Bloomberg Center for Physics and Astronomy (a 5 minute walk). The JHMI Shuttle schedule is available here (http://ts.jhu.edu/Shuttles/Shuttle_Schedules/Homewood_JHMI_Shuttle_Schedule.pdf).

For those traveling to MedHacks by train (Amtrak and MARC Penn Line) via Baltimore Penn Station, the JHMI shuttle stops at Penn Station and heads north to the Homewood Campus (its northernmost stop). Taxis are also available at Penn Station for the 10 minute drive to the Homewood Campus, and should cost approximately $7.

If you have any questions regarding travel, please email us at medhacks@jhu.edu.

**Comment by ronboger** [comment]
could you also add info about the JHMI?

**Comment by ronboger** [comment]
and penn station/MARC?

**Comment by dhamburger** [comment]
Done. Can you make the JHMI schedule linked?
