### ISSUE TITLE
Add speaker section and bio

### ISSUE THREAD

**Issue by errcHuang** [ronnyb29/medhacksSite#55]
We have a confirmed speaker, Jini Kim, so it'd be cool to have a section on the website with her bio.

"Ms. Jini Kim is the CEO of Nuna, a startup that provides healthcare data analytics for self-insured employers and the government, including the Centers for Medicare and Medicaid Services. 

Formerly a product manager with Google Health and the Go team, Kim also worked with the White House to save the Healthcare.gov site, which had been plagued by technical glitches." 

Picture: https://fortunedotcom.files.wordpress.com/2015/10/screen-shot-2015-10-08-at-6-00-38-pm.png?w=719&h=717

**Comment by ronboger** [comment]
wait, no we don't

**Comment by ronboger** [comment]
she's not confirmed at all

**Comment by ronboger** [comment]
she was interested but can't make it anymore, but one of their execs might come
