### ISSUE TITLE
make the background behind the sponsors white

### ISSUE THREAD

**Issue by ronboger** [ronnyb29/medhacksSite#56]
or make the white pngs transparent because it shows on the site and looks bad

**Comment by vicmart** [comment]
Do you have a screenshot? Because this is what I see and it looks fine: 
<img width="1085" alt="screen shot 2016-07-31 at 5 38 30 pm" src="https://cloud.githubusercontent.com/assets/10588830/17279577/b1a7c156-5745-11e6-91b0-960026fdb255.png">

**Comment by vicmart** [comment]
never mind I see your point lol
