### ISSUE TITLE
Link to location on map

### ISSUE THREAD

**Issue by dwesty** [ronnyb29/medhacksSite#7]
Put this jawn (https://goo.gl/maps/VF5wL) here:

![image](https://cloud.githubusercontent.com/assets/6182431/8712214/83cea5a6-2b27-11e5-823f-684730e6515b.png)

...just an href....embed would not work w current layout

**Comment by ronboger** [comment]
done - let me know if that's what you envisioned

**Comment by ronboger** [comment]
(sorry to steal the github issues you assigned to yourself)
