### ISSUE TITLE
Default Msft Office styles on Sponsorship page....eewww!

### ISSUE THREAD

**Issue by dwesty** [ronnyb29/medhacksSite#8]
First, I'm obsessed with the nucleotide-->nucleus theme here.

But @ronnyb29 can you send me the orig. Some basic design work would behoove us. I cringe at the office defaults. There's no reason in 2015 (or ever) that a company should have the _default_ style for shapes include a shadow with that cheezy border and a gradient shade of blue more drab than USSR era apartment complexes.

![image](https://cloud.githubusercontent.com/assets/6182431/8712250/fce07708-2b27-11e5-87a1-db628cc332b9.png)

https://www.youtube.com/watch?v=JltEXpbGM8s

**Comment by dwesty** [comment]
Also, I think this overall design is very effective at communicating the levels. It's more clever than checkboxes

**Comment by ronboger** [comment]
will do, thanks David!

yeah, one of our sponsors said he needed a PhD to understand the
sponsorship terms...

**Comment by dwesty** [comment]
lol...was he talking about before or after this document existed?

**Comment by ronboger** [comment]
i sent it to him... i'l forward you the exact email lol

**Comment by dwesty** [comment]
Cool. And woops...didn't mean to hit close there.
